---
version: "3.9"

services:
  postgres:
    deploy: 
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    container_name: postgres
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    networks:
      - pia

  pgweb:
    deploy: 
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    container_name: pgweb
    image: sosedoff/pgweb:latest
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:postgres@postgres:5432/db?sslmode=disable
    ports:
      - 8081:8081
    networks:
      - pia
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s


volumes:
  data:
    name: pgweb_postgres

networks:
  pia:
    name: pia